import pathlib,re,json
P=pathlib.Path
p=P('src/javascript/Application.js');s=p.read_text();s=s.replace("import ThreejsJourney from './ThreejsJourney.js'",'');s=s.replace('        this.setTitle()','').replace('        this.setThreejsJourney()','');s=re.sub(r'    setTitle\(\).*?(?=    /\*\*\n     \* Destructor)', '',s,flags=re.S);s=s.replace('this.renderer.setPixelRatio(2)',"this.renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, matchMedia('(pointer: coarse)').matches ? 1.25 : 1.75))");p.write_text(s)
p=P('src/javascript/World/Controls.js');s=p.read_text().replace("            switch(_event.code)","            if(document.querySelector('dialog[open]') || _event.target.closest?.('button, input, select, a')) return\n            if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(_event.code)) _event.preventDefault()\n            switch(_event.code)");s=s.replace('if(!document.hidden)','if(document.hidden)');p.write_text(s)
p=P('src/javascript/World/index.js');s=p.read_text().replace('        this.setEasterEggs()','');s=s.replace('            this.startingScreen.area.deactivate()',"            if(this.physics) return\n            this.startingScreen.area.deactivate()");s=re.sub(r"this.startingScreen.loadingLabel.image.src = 'data:[^']+'","this.startingScreen.loadingLabel.image.src = labelTexture(['CARREGANDO']).image.toDataURL()",s);s=re.sub(r"this.startingScreen.startLabel.image.src = 'data:[^']+'","this.startingScreen.startLabel.image.src = labelTexture(['EXPLORAR']).image.toDataURL()",s);s="import { labelTexture } from '../portfolio/sceneText.js'\n"+s;p.write_text(s)
p=P('src/javascript/Resources.js');s=p.read_text();s=s.replace('        ])',"        ].filter(resource => !/^(intro[B RUNOSIM]|introCreative|introDev|information|crossroads|projects(?!Board)|distinction|konami|wig)/.test(resource.name)))",1);p.write_text(s)
p=P('src/javascript/World/Sections/IntroSection.js');s=p.read_text();s="import { floorLabel } from '../../portfolio/sceneText.js'\n"+s;s=s.replace('        this.setStatic()','').replace('        this.setOtherInstructions()','');s=re.sub(r'    setTitles\(\).*?(?=    setTiles\(\))',"    setTitles()\n    {\n        this.container.add(floorLabel(['ALLAN', 'SELEGUIM'], 15, 5, 0, 5))\n        this.container.add(floorLabel(['ENGENHEIRO DE SOFTWARE SÊNIOR', 'SOROCABA • SÃO PAULO • BRASIL'], 12, 2, 0, 9))\n    }\n\n",s,flags=re.S);s=s.replace('this.config.touch ? this.resources.items.introInstructionsControlsTexture : this.resources.items.introInstructionsArrowsTexture',"labelTexture(['USE AS SETAS OU WASD'])");s=s.replace('import { floorLabel }','import { floorLabel, labelTexture }');p.write_text(s)
p=P('src/javascript/World/Sections/CrossroadsSection.js');s=p.read_text();s="import { floorLabel } from '../../portfolio/sceneText.js'\n"+s;s=re.sub(r'    setStatic\(\).*?(?=    setTiles\(\))',"    setStatic()\n    {\n        this.container.add(floorLabel(['← SOBRE MIM', 'PROJETOS →', '↑ INÍCIO'], 16, 7, this.x, this.y))\n    }\n\n",s,flags=re.S);p.write_text(s)
p=P('src/javascript/World/Sections/ProjectsSection.js');s=p.read_text();s="import profile from '../../portfolio/data.json'\nimport { labelTexture, projectImage } from '../../portfolio/sceneText.js'\n"+s;s=re.sub(r'    setList\(\).*?(?=    setZone\(\))',"    setList()\n    {\n        this.list = profile.projects.map(project => ({\n            name: project.name,\n            imageSources: [projectImage(project)],\n            floorTexture: labelTexture([project.name, project.stack.join(' • '), 'VER REPOSITÓRIO']),\n            link: { href: project.repository, x: -4.8, y: -3, halfExtents: { x: 3.2, y: 1.5 } },\n            distinctions: []\n        }))\n    }\n\n",s,flags=re.S);p.write_text(s)
p=P('src/javascript/World/Sections/Project.js');s=p.read_text().replace("window.open(this.link.href, '_blank')","window.open(this.link.href, '_blank', 'noopener,noreferrer')");p.write_text(s)
P('vite.config.js').write_text("import glsl from 'vite-plugin-glsl'\nexport default { root: 'src', publicDir: '../static', base: './', server: { host: '127.0.0.1', open: false }, build: { outDir: '../dist', emptyOutDir: true, sourcemap: false }, plugins: [glsl()] }\n")
p=P('package.json');d=json.loads(p.read_text());d['name']='allan-seleguim-portfolio';d['version']='1.0.0';d['scripts']['preview']='vite preview';d['engines']={'node':'>=22.12.0'};d['dependencies'].pop('vite-plugin-restart',None);p.write_text(json.dumps(d,indent=2)+'\n')
